### ISSUE TITLE
Git Strategy

### ISSUE THREAD

**Issue by alfredopizana** [CristopherCastaneda/devto#7]
Start using git branching strategy. I've seen that you have been already using it, try to go to the next level and assign a different reviewer and roles. Block main branch to avoid pushing it. 

**main** branch should only be used to receive changes from pull requests.
Here is a video that could help as a guidance, this video is from a guy on microsoft: 
https://www.youtube.com/watch?v=ykZbBD-CmP8
Another one:
https://www.youtube.com/watch?v=aJnFGMclhU8

Discuss and share this with all team members. Let me know if you have any question or feedback.

**Comment by CristopherCastaneda** [comment]
git stategy has been implemented, thanks for you recommented
